function com_vxplo_Base(){var N='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',gb='"><\/script>',X='#',zb='&',Dc='.cache.js',Z='/',jb='//',Vb='017B9E98EED2BDBC680F7DB7C13DAEC9',Xb='0EC241385927A14D6AE867B2059A823F',Yb='169A8BF95EBC53E31736BBBEB6936F1F',Zb='1CEA8A6AF771453CA7963A3C7D27C83C',$b='23FD334D229E333E356DCE590111EDFB',_b='28D1261A28914882780B80AA3EEFD597',ac='4450536DF26A51ABD7DE83071EA1C6F8',bc='4C9ACA3E1242CB94E06381B72991B12F',cc='682C45032E76FE49C93FD6A74464FAE1',dc='767D9FF3402A0EC1E3F24039FFD6ABE5',ec='7DD2E5FADDDD7E5472A5C87B240EEB02',fc='8F310DF88EE1864AFCABE1C456B883BA',sc=':',nb='::',fb='<script id="',qb='=',Y='?',gc='A31F45E09D6BE64876E91431EFBC9EE0',hc='B8A1578075DA73BFE7648FF8582C128F',ic='BF548D332E5B93D6CBCEB1844D3A081D',sb='Bad handler "',jc='C99DB15F67B587759FF39E29C84649C1',kc='CDE075516E9DCD72DA7187B262695EF0',lc='CFD1F4370557D6B43F3EA2838E510B14',Sb='Cross-site hosted mode not yet implemented. See issue ',mc='D2A3455D4BD89CCBD97B65F6760AE580',nc='D70B5033127E1C8286B7DA8EF729A99D',oc='DC4B01B6F087619DDE26798569DA854D',pc='DDAD53DC23F9CDA4B96AB4566122C5A2',zc='DOMContentLoaded',qc='F54E68B31E894D35AD09EA763160E910',rc='FE0F3333754DCAA02A26B7E4DDA411FB',hb='SCRIPT',Cb='Unexpected exception in locale detection, using default: ',Pb='[\\?&]editor=([^&#]*)',Bb='_',Ab='__gwt_Locale',eb='__gwt_marker_com.vxplo.Base',ib='base',ab='baseUrl',R='begin',Q='bootstrap',_='clear.cache.gif',O='com.vxplo.Base',cb='com.vxplo.Base.nocache.js',mb='com.vxplo.Base::',pb='content',xb='default',Rb='editor',W='end',Lb='gecko',Mb='gecko1_8',S='gwt.codesvr=',T='gwt.hosted=',U='gwt.hybrid',tc='gwt/standard/vxplo.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',yc='head',xc='href',Tb='http://code.google.com/p/google-web-toolkit/issues/detail?id=2079',Kb='ie6',Jb='ie8',Ib='ie9',$='img',uc='link',Ac='loadExternalRefs',wb='locale',yb='locale=',kb='meta',Bc='moduleRequested',V='moduleStartup',Hb='msie',lb='name',Eb='opera',vc='rel',Gb='safari',bb='script',Ub='selectingPermutation',P='startup',wc='stylesheet',Cc='text/javascript',db='undefined',Nb='unknown',Db='user.agent',Qb='viewer',Ob='vxbuildtype',Fb='webkit',Wb='zh';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s=N,t={},u=[],v=[],w=[],x=0,y,z;o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:R});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=m.location.search;return (c.indexOf(S)!=-1||(c.indexOf(T)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(U)==-1}catch(a){}A=function(){return b};return b}
function B(){if(q&&r){q(y,O,s,x);o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:V,millis:(new Date).getTime(),type:W})}}
function C(){function e(a){var b=a.lastIndexOf(X);if(b==-1){b=a.length}var c=a.indexOf(Y);if(c==-1){c=a.length}var d=a.lastIndexOf(Z,Math.min(c,b));return d>=0?a.substring(0,d+1):N}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement($);b.src=a+_;a=e(b.src)}return a}
function g(){var a=F(ab);if(a!=null){return a}return N}
function h(){var a=n.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(cb)!=-1){return e(a[b].src)}}return N}
function i(){var a;if(typeof isBodyLoaded==db||!isBodyLoaded()){var b=eb;var c;n.write(fb+b+gb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=hb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return N}
function j(){var a=n.getElementsByTagName(ib);if(a.length>0){return a[a.length-1].href}return N}
function k(){var a=n.location;return a.href==a.protocol+jb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==N){l=h()}if(l==N){l=i()}if(l==N){l=j()}if(l==N&&k()){l=e(n.location.href)}l=f(l);s=l;return l}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,N);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=N}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
v[wb]=function(){var b=null;var c=xb;try{if(!b){var d=location.search;var e=d.indexOf(yb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(zb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(wb)}if(!b){b=m[Ab]}if(b){c=b}while(b&&!E(wb,b)){var h=b.lastIndexOf(Bb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Cb+a)}m[Ab]=c;return b||xb};u[wb]={'default':0,zh:1};v[Db]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Eb)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1}())return Gb;if(function(){return b.indexOf(Hb)!=-1&&n.documentMode>=9}())return Ib;if(function(){return b.indexOf(Hb)!=-1&&n.documentMode>=8}())return Jb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;return Nb};u[Db]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};v[Ob]=function(){var a=new RegExp(Pb);if(a.exec(window.location.href)==null){return Qb}else{return Rb}};u[Ob]={editor:0,viewer:1};com_vxplo_Base.onScriptLoad=function(a){com_vxplo_Base.onScriptLoad=null;q=a;B()};if(A()){alert(Sb+Tb);return}D();C();o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:Ub});var I;try{G([xb,Jb,Qb],Vb);G([Wb,Eb,Rb],Xb);G([Wb,Jb,Rb],Yb);G([xb,Gb,Qb],Zb);G([Wb,Jb,Qb],$b);G([Wb,Kb,Rb],_b);G([xb,Jb,Rb],ac);G([xb,Ib,Qb],bc);G([Wb,Ib,Rb],cc);G([xb,Gb,Rb],dc);G([Wb,Gb,Rb],ec);G([xb,Eb,Qb],fc);G([Wb,Kb,Qb],gc);G([Wb,Mb,Rb],hc);G([xb,Mb,Rb],ic);G([xb,Kb,Rb],jc);G([Wb,Eb,Qb],kc);G([xb,Mb,Qb],lc);G([Wb,Mb,Qb],mc);G([xb,Kb,Qb],nc);G([xb,Eb,Rb],oc);G([Wb,Ib,Qb],pc);G([xb,Ib,Rb],qc);G([Wb,Gb,Qb],rc);I=w[H(wb)][H(Db)][H(Ob)];var J=I.indexOf(sc);if(J!=-1){x=Number(I.substring(J+1));I=I.substring(0,J)}}catch(a){return}var K;function L(){if(!r){r=true;if(!__gwt_stylesLoaded[tc]){var a=n.createElement(uc);__gwt_stylesLoaded[tc]=a;a.setAttribute(vc,wc);a.setAttribute(xc,s+tc);n.getElementsByTagName(yc)[0].appendChild(a)}B();if(n.removeEventListener){n.removeEventListener(zc,L,false)}if(K){clearInterval(K)}}}
if(n.addEventListener){n.addEventListener(zc,function(){L()},false)}var K=setInterval(function(){if(/loaded|complete/.test(n.readyState)){L()}},50);o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Q,millis:(new Date).getTime(),type:W});o&&o({moduleName:O,sessionId:p,subSystem:P,evtGroup:Ac,millis:(new Date).getTime(),type:R});window.__gwtStatsEvent&&window.__gwtStatsEvent({moduleName:O,sessionId:window.__gwtStatsSessionId,subSystem:P,evtGroup:Ac,millis:(new Date).getTime(),type:W});window.__gwtStatsEvent&&window.__gwtStatsEvent({moduleName:O,sessionId:window.__gwtStatsSessionId,subSystem:P,evtGroup:V,millis:(new Date).getTime(),type:Bc});var M=document.createElement(bb);M.type=Cc;M.src=s+I+Dc;n.body.appendChild(M)}
com_vxplo_Base();